# Generated by Django 5.2.5 on 2025-08-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('username', models.TextField(unique=True)),
                ('password', models.CharField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.IntegerField()),
                ('role', models.CharField(choices=[('USER', 'user'), ('ADMIN', 'admin')], default='USER', serialize=False)),
            ],
        ),
    ]
