# Generated by Django 5.2.5 on 2025-08-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
